# Generated by Django 4.2.5 on 2023-09-29 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_person'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='place',
            new_name='places',
        ),
    ]
