# Generated by Django 4.2.5 on 2023-09-29 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_demo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='demo',
        ),
    ]
